apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: university-chatbot
spec:
  type: LoadBalancer
  selector:
    app: university-rag-chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      